# Generated by Django 3.2.4 on 2021-06-20 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_subscriber_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
