# Generated by Django 3.2.4 on 2021-07-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_testy'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='testymore',
            field=models.CharField(default='tests', max_length=100),
        ),
    ]
