# Generated by Django 3.2.4 on 2021-07-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_testymore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='testy',
        ),
        migrations.RemoveField(
            model_name='account',
            name='testymore',
        ),
    ]
