# Generated by Django 3.2.4 on 2021-06-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_subscriber_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
