# Generated by Django 3.2.4 on 2021-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210702_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.CharField(choices=[('free', 'free'), ('pro', 'pro')], default='free', max_length=10),
        ),
    ]
