# Generated by Django 3.2.4 on 2021-08-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_messages'),
        ('email_messages', '0002_message_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='automations',
            field=models.ManyToManyField(to='automations.Automation'),
        ),
    ]
