# Generated by Django 3.2.4 on 2021-08-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_automation_messages'),
        ('email_messages', '0003_message_automations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='automations',
            field=models.ManyToManyField(blank=True, to='automations.Automation'),
        ),
    ]
