# Generated by Django 3.2.4 on 2021-06-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='subscribers.Subscriber'),
        ),
    ]
