# Generated by Django 3.2.4 on 2021-06-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0003_alter_tag_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(blank=True, to='subscribers.Tag'),
        ),
    ]
