# Generated by Django 3.2.4 on 2021-08-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_messages', '0002_message_date_created'),
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='messages',
            field=models.ManyToManyField(to='email_messages.Message'),
        ),
    ]
