# Generated by Django 3.2.4 on 2021-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_messages', '0003_message_automations'),
        ('automations', '0002_automation_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='messages',
            field=models.ManyToManyField(blank=True, to='email_messages.Message'),
        ),
    ]
